# Generated by Django 3.1.5 on 2021-02-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image_url',
            field=models.ImageField(upload_to='pets'),
        ),
    ]
