# Generated by Django 3.1.5 on 2021-01-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20210122_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.profile'),
        ),
    ]
