# Generated by Django 3.1.5 on 2021-01-23 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_expenses_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.profile'),
        ),
    ]
