# Generated by Django 3.1.5 on 2021-01-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=20)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
    ]
