# Generated by Django 3.1.5 on 2021-01-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0005_game2_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game2',
            name='level',
            field=models.IntegerField(choices=[('Easy', 0), ('Medium', 1), ('Hard', 1)], default=0),
        ),
    ]
