# Generated by Django 3.1.5 on 2021-01-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0006_auto_20210116_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game2',
            name='level',
            field=models.IntegerField(choices=[('Easy', 'EA'), ('Medium', 'ME'), ('Hard', 'HA')], default=0),
        ),
    ]
