# Generated by Django 3.1.5 on 2021-01-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0007_auto_20210116_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game2',
            name='level',
            field=models.CharField(choices=[('EA', 'Easy'), ('ME', 'Medium'), ('HA', 'Hard')], default=0, max_length=2),
        ),
    ]
