# Generated by Django 3.1.5 on 2021-01-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django102', '0008_auto_20210116_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game2',
            name='level',
            field=models.CharField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=0, max_length=2),
        ),
    ]
